server:
  port: 8080

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5400/manageit
    username: manageit
    password: admin
    driver-class-name: org.postgresql.Driver



